[package]
name = "egui-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { path = "../../rust-vendor/egui/eframe" }
image = "0.22.1"
rand = "0.8.5"