[package]
name = "cdl-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdl-parser = { path = "../cdl-parser" }
serde = { version = "1.0.197" , features =["derive","rc"] }
serde_json = "1.0.114"